language: rust
cache: cargo
sudo: required
services: docker

rust:
  - stable
  - beta

env:
  matrix:
    - TARGET="x86_64-unknown-linux-gnu"
    - TARGET="mips-unknown-linux-gnu"
    - TARGET="mipsel-unknown-linux-gnu"
    - TARGET="mips64-unknown-linux-gnuabi64"
    - TARGET="mips64el-unknown-linux-gnuabi64"
    - TARGET="aarch64-unknown-linux-gnu"

before_install:
  - cargo install cross --force

script:
  - cross build --target $TARGET --verbose --all
  - cross test --target $TARGET --verbose --all

matrix:
  allow_failures:
    - rust: beta
  fast_finish: true
  include:
    - rust: stable
      env:
      before_install:
      script:
        - rustup component add rustfmt-preview
        - cargo fmt --all -- --check
    - name: Clippy
      rust: stable
      env:
      before_install:
      before_script:
        - rustup component add clippy-preview
      script:
        - cargo clippy --all-targets --all-features -- -D warnings
    - name: Benchmark
      rust: stable
      env:
      before_install:
      script:
        - cargo bench
    - rust: stable
      env:
      before_install:
      before_script:
        - docker run -d -p 8545:8545 trufflesuite/ganache-cli:latest -a 10 -i 42 -e 1000 --debug
      script:
        # Runs expensive testnet tests
        - cargo test --verbose -- --ignored testnet
