[package]
name = "clarity"
version = "0.1.0"
authors = ["Michał Papierski <michal@papierski.net>"]

[dependencies]
serde = "1.0"
serde-rlp = "0.1"
num-bigint = "0.2"
num-traits = "0.2"
failure = "0.1"
serde_bytes = "0.10"
sha3 = "0.7"
# TODO: Swap to 0.11 once new release is rolled up with my PR that fixes big endian support https://github.com/rust-bitcoin/rust-secp256k1/pull/64
secp256k1 = { git = "https://github.com/rust-bitcoin/rust-secp256k1/", branch = "master" }